<?php if ($block->getReviews() && count($block->getReviews())): ?>
	<div class="customer-review" style="background-image: url('<?php echo $block->getUrl(); ?>pub/media/wysiwyg/bg_bottom_02.jpg');">
		<div class="title"><span>customer show<i></i></span></div>
		<div class="content">
			<?php foreach ($block->getReviews() as $_review): ?>
			<div class="item">
				<div class="customer-review-image">
					<img src="<?php echo $block->getUrl();echo $block->getReviewFeaturedImage($_review->getAdvancedImg()); ?>"/>
				</div>
				<div class="customer-review-nickname">
					<?php echo $block->escapeHtml($_review->getNickname()); ?>
				</div>
				<div class="customer-review-time">
					<?php echo $block->escapeHtml($_review->getCreatedAt()); ?>
				</div>
			</div>
			<?php endforeach; ?>
		</div>
	</div>
<?php endif; ?>